// Code generated by github.com/nakatamixi/gql-template DO NOT EDIT.
package model

import (
    "time"
)

{{- range $ti, $t  := .Types }}
  {{- if not $t.BuiltIn }}
    {{- if eq $t.Kind "OBJECT" }}
      {{- if and (ne $t.Name "Query") (ne $t.Name "Mutation") (ne $t.Name "Subscription") }}
type {{ $t.Name | title }} struct {
        {{- range $fi, $f  := $t.Fields }}
    {{ $f.Name | title }}   {{ GoType $f }}
        {{- end }}
}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
